add trap command to main script

diff --git a/deployment-local/local-tg b/deployment-local/local-tg
--- a/deployment-local/local-tg
+++ b/deployment-local/local-tg
@@ -1,6 +1,26 @@
 #!/bin/sh
 
-if [ "$1" = "startup-jenkins" ]; then
+shutdown_localTG()
+{
+  if [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080) -eq 302 >/dev/null 2>&1 ]
+  then
+    echo "shutting down tomcat....."
+    ./tomcat/apache-tomcat-8.5.43/bin/shutdown.sh >/dev/null
+  fi
+
+  if [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8082) -eq 200 >/dev/null 2>&1 ]
+  then
+    echo "shutting down H2 server....."
+    java -cp lib/h2-*.jar org.h2.tools.Server -tcpShutdown tcp://localhost:9092  >/dev/null 2>&1
+  fi
+
+  exit 1
+}
+
+if [ "$1" = "startup" ]; then
+
+    trap 'shutdown_localTG' 2
+
     echo "__          _______  ____ ___    _______        _    _____      _     _    _       ____   _____   ___   _      "
     echo "\ \        / / ____|/ __ \__ \  |__   __|      | |  / ____|    (_)   | |  | |    /  __  \/ _____|/    \| |     "
     echo " \ \  /\  / / (___ | |  | | ) |    | | ___  ___| |_| |  __ _ __ _  __| |  | |    | |  | | |     | /__\ | |     "
@@ -15,12 +35,13 @@ if [ "$1" = "startup-jenkins" ]; then
     chmod +x ./scripts/add_config_provider_files.sh
     chmod +x ./testgrid/testgrid-home/testgrid-dist/WSO2-TestGrid/*
 
-    if [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080) -eq 000 ]
+    if [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080) -eq 000 >/dev/null 2>&1 ]
     then
 
-      ./tomcat/apache-tomcat-8.5.43/bin/startup.sh
+      echo "starting tomcat....."
+      ./tomcat/apache-tomcat-8.5.43/bin/startup.sh >/dev/null
 
-    	while [ $(curl -s -w "%{http_code}" http://localhost:8080/admin -o /dev/null) -eq 000 ]
+    	while [ $(curl -s -w "%{http_code}" http://localhost:8080/admin -o /dev/null) -eq 000 >/dev/null 2>&1 ]
     	do
       	  sleep 1
     	done
@@ -39,26 +60,18 @@ if [ "$1" = "startup-jenkins" ]; then
     fi
 
 
-    if [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8082) -eq 000 ]
+    if [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8082) -eq 000 >/dev/null 2>&1 ]
     then
         echo "starting H2 server....."
-        java -jar lib/h2-*.jar  -baseDir ./h2db &> /dev/null &
+        java -jar lib/h2-*.jar -baseDir ./h2db >/dev/null 2>&1 &
+
     fi
 
-
-elif [ "$1" = "shutdown-jenkins" ]
+elif [ "$1" = "shutdown" ]
 then
 
-   if [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080) -eq 302 ]
-   then
-     ./tomcat/apache-tomcat-8.5.43/bin/shutdown.sh
-   fi
-
-   if [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8082) -eq 200 ]
-   then
-     java -cp lib/h2-*.jar org.h2.tools.Server -tcpShutdown tcp://localhost:9092
-   fi
+  shutdown_localTG
 
 else
-   echo "Invalid command \nValid commands are..\n./local-tg startup-jenkins - to startup local-tg\n./local-tg shutdown-jenkins - to shutdown local-tg"
+   echo "Invalid command \nValid commands are..\n./local-tg startup - to startup local-tg\n./local-tg shutdown - to shutdown local-tg"
 fi
