Add OPEN_JDK11

diff --git a/jobs/intg-test-resources/wso2-intg-test-cfn.yaml b/jobs/intg-test-resources/wso2-intg-test-cfn.yaml
--- a/jobs/intg-test-resources/wso2-intg-test-cfn.yaml
+++ b/jobs/intg-test-resources/wso2-intg-test-cfn.yaml
@@ -139,6 +139,7 @@ Parameters:
       - ORACLE_JDK8
       - ADOPT_OPEN_JDK8
       - CORRETTO_JDK8
+      - OPEN_JDK11
   MavenVersion:
     Type: String
     Default: '3.3.9'
@@ -269,18 +270,18 @@ Resources:
           ulimit -Sn
 
           setup_java_env() {
-          JDK=ORACLE_JDK8
-          source /etc/environment
+            JDK=ORACLE_JDK8
+            source /etc/environment
 
-          echo JDK_PARAM=${JDK} >> /opt/testgrid/java.txt
-          REQUESTED_JDK_PRESENT=$(grep "^${JDK}=" /etc/environment | wc -l)
-          if [ $REQUESTED_JDK_PRESENT = 0 ]; then
-          printf "The requested JDK, ${JDK}, not found in /etc/environment: \n $(cat /etc/environment)."
-          exit 1; // todo: inform via cfn-signal
-          fi
+            echo JDK_PARAM=${JDK} >> /opt/testgrid/java.txt
+            REQUESTED_JDK_PRESENT=$(grep "^${JDK}=" /etc/environment | wc -l)
+            if [ $REQUESTED_JDK_PRESENT = 0 ]; then
+              printf "The requested JDK, ${JDK}, not found in /etc/environment: \n $(cat /etc/environment)."
+              exit 1; // todo: inform via cfn-signal
+            fi
             JAVA_HOME=$(grep "^${JDK}=" /etc/environment | head -1 | sed "s:${JDK}=\(.*\):\1:g" | sed 's:"::g')
 
-           echo ">> Setting up JAVA_HOME ..."
+            echo ">> Setting up JAVA_HOME ..."
             JAVA_HOME_EXISTS=$(grep -r "JAVA_HOME=" /etc/environment | wc -l  )
             if [ $JAVA_HOME_EXISTS = 0 ]; then
               echo ">> Adding JAVA_HOME entry."
@@ -288,11 +289,11 @@ Resources:
             else
               echo ">> Updating JAVA_HOME entry."
               sed -i "/JAVA_HOME=/c\JAVA_HOME=$JAVA_HOME" /etc/environment
-          fi
+            fi
             source /etc/environment
             echo "export JAVA_HOME=$JAVA_HOME" >> /etc/profile
-                      source /etc/profile
-            }
+            source /etc/profile
+          }
 
           mkdir -p /opt/testgrid/workspace
           #TODO: We need to figure out the default user in the system.
