Fix cf issues

diff --git a/jobs/intg-test-resources/wso2-intg-test-cfn.yaml b/jobs/intg-test-resources/wso2-intg-test-cfn.yaml
--- a/jobs/intg-test-resources/wso2-intg-test-cfn.yaml
+++ b/jobs/intg-test-resources/wso2-intg-test-cfn.yaml
@@ -124,6 +124,10 @@ Parameters:
     AllowedValues:
       - OPEN_JDK8
       - ORACLE_JDK8
+  CustomUserData:
+   Type: String
+   Default: "echo"
+   Description: Enter custome user data scripts here.
 Mappings:
   DB2Licence:
     mysql:
@@ -216,35 +220,36 @@ Resources:
       ]
       UserData: !Base64
         'Fn::Sub': |
+          #cloud-boothook
           #!/bin/bash
           set -e
           set -o xtrace
 
           setup_java_env() {
-              source /etc/environment
+          JDK=ORACLE_JDK8
+          source /etc/environment
 
-              echo JDK_PARAM=${JDK} >> /opt/wso2/java.txt
-              REQUESTED_JDK_PRESENT=$(grep "^${JDK}=" /etc/environment | wc -l)
-              if [ $REQUESTED_JDK_PRESENT = 0 ]; then
-                printf "The requested JDK, ${JDK}, not found in /etc/environment: \n $(cat /etc/environment)."
-                exit 1; // todo: inform via cfn-signal
-              fi
-              JAVA_HOME=$(grep "^${JDK}=" /etc/environment | head -1 | sed "s:${JDK}=\(.*\):\1:g" | sed 's:"::g')
+          echo JDK_PARAM=${JDK} >> /opt/wso2/java.txt
+          REQUESTED_JDK_PRESENT=$(grep "^${JDK}=" /etc/environment | wc -l)
+          if [ $REQUESTED_JDK_PRESENT = 0 ]; then
+          printf "The requested JDK, ${JDK}, not found in /etc/environment: \n $(cat /etc/environment)."
+          exit 1; // todo: inform via cfn-signal
+          fi
+            JAVA_HOME=$(grep "^${JDK}=" /etc/environment | head -1 | sed "s:${JDK}=\(.*\):\1:g" | sed 's:"::g')
 
-              echo ">> Setting up JAVA_HOME ..."
-              JAVA_HOME_EXISTS=$(grep -r "JAVA_HOME=" /etc/environment | wc -l  )
-              if [ $JAVA_HOME_EXISTS = 0 ]; then
-                  echo ">> Adding JAVA_HOME entry."
-                  echo JAVA_HOME=$JAVA_HOME >> /etc/environment
-              else
-                  echo ">> Updating JAVA_HOME entry."
-                  sed -i "/JAVA_HOME=/c\JAVA_HOME=$JAVA_HOME" /etc/environment
-              fi
-              source /etc/environment
-
-              echo "export JAVA_HOME=$JAVA_HOME" >> /etc/profile
-              source /etc/profile
-          }
+           echo ">> Setting up JAVA_HOME ..."
+            JAVA_HOME_EXISTS=$(grep -r "JAVA_HOME=" /etc/environment | wc -l  )
+            if [ $JAVA_HOME_EXISTS = 0 ]; then
+              echo ">> Adding JAVA_HOME entry."
+              echo JAVA_HOME=$JAVA_HOME >> /etc/environment
+            else
+              echo ">> Updating JAVA_HOME entry."
+              sed -i "/JAVA_HOME=/c\JAVA_HOME=$JAVA_HOME" /etc/environment
+          fi
+            source /etc/environment
+            echo "export JAVA_HOME=$JAVA_HOME" >> /etc/profile
+                      source /etc/profile
+            }
 
           mkdir -p /opt/wso2/workspace
           #TODO: We need to figure out the default user in the system.
@@ -257,16 +262,14 @@ Resources:
           wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
           tar -xvzf apache-maven-3.3.9-bin.tar.gz
           ln -fs apache-maven-3.3.9 maven
-          export MAVEN_OPTS="-Xmx2048m -Xms256m"
-          export PATH=/opt/wso2/maven/bin/:$PATH
+          echo 'export MAVEN_OPTS="-Xmx2048m -Xms256m"' >> /etc/environment
+          echo 'export M3_HOME=/opt/wso2/workspace/maven' >> /etc/environment
+          echo PATH=/opt/wso2/workspace/maven/bin/:$PATH >> /etc/environment
 
-          # echo "Cloning and running product-apim"
-          # git clone --branch v2.2.0-update7 http://github.com/wso2/product-apim.git
-          # cd product-apim
-          # mvn clean install
+          source /etc/environment
 
-          apt-get --purge remove -y git
           cat /dev/null > ~/.bash_history && history -c
+          ${CustomUserData}
       Tags:
         - Key: Name
           Value: wso2-apim-intg-node
