Increases the root disk size to 50GB
Provides infrastructure provisioning scripts for APIM integration test jobs

Fixes #811

diff --git a/core/src/main/resources/intg-test-resources/wso2-intg-test-cfn.yaml b/core/src/main/resources/intg-test-resources/wso2-intg-test-cfn.yaml
--- a/core/src/main/resources/intg-test-resources/wso2-intg-test-cfn.yaml
+++ b/core/src/main/resources/intg-test-resources/wso2-intg-test-cfn.yaml
@@ -184,19 +184,53 @@ Resources:
       InstanceType: !Ref WSO2InstanceType
       KeyName: !Ref EC2KeyPair
       Monitoring: 'false'
+      "BlockDeviceMappings" : [
+         {
+            "DeviceName" : "/dev/sda1",
+            "Ebs" : { "VolumeSize" : "50" }
+         },
+      ]
       UserData: !Base64
         'Fn::Sub': |
           #!/bin/bash
           set -e
+          set -o xtrace
+
+          setup_java_env() {
+              source /etc/environment
+
+              echo JDK_PARAM=${JDK} >> /opt/wso2/java.txt
+              REQUESTED_JDK_PRESENT=$(grep "^${JDK}=" /etc/environment | wc -l)
+              if [ $REQUESTED_JDK_PRESENT = 0 ]; then
+                printf "The requested JDK, ${JDK}, not found in /etc/environment: \n $(cat /etc/environment)."
+                exit 1; // todo: inform via cfn-signal
+              fi
+              JAVA_HOME=$(grep "^${JDK}=" /etc/environment | head -1 | sed "s:${JDK}=\(.*\):\1:g" | sed 's:"::g')
+
+              echo ">> Setting up JAVA_HOME ..."
+              JAVA_HOME_EXISTS=$(grep -r "JAVA_HOME=" /etc/environment | wc -l  )
+              if [ $JAVA_HOME_EXISTS = 0 ]; then
+                  echo ">> Adding JAVA_HOME entry."
+                  echo JAVA_HOME=$JAVA_HOME >> /etc/environment
+              else
+                  echo ">> Updating JAVA_HOME entry."
+                  sed -i "/JAVA_HOME=/c\JAVA_HOME=$JAVA_HOME" /etc/environment
+              fi
+              source /etc/environment
+
+              echo "export JAVA_HOME=$JAVA_HOME" >> /etc/profile
+              source /etc/profile
+          }
+
           apt-get -y install git
-          mkdir /opt/wso2
+          mkdir -p /opt/wso2
           cd /opt/wso2
 
           setup_java_env
           echo "Installing Apache Maven"
           wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
           tar -xvzf apache-maven-3.3.9-bin.tar.gz
-          ln -s apache-maven-3.3.9 maven
+          ln -fs apache-maven-3.3.9 maven
           export MAVEN_OPTS="-Xmx2048m -Xms256m"
           export PATH=/opt/wso2/maven/bin/:$PATH
 
@@ -207,39 +241,6 @@ Resources:
 
           apt-get --purge remove -y git
           cat /dev/null > ~/.bash_history && history -c
-
-          setup_java_env() {
-              source /etc/environment
-              if [ ${JDK} = "JDK7" ]; then
-                  JAVA_HOME=${JDK7}
-              elif [ ${JDK} = "JDK8" ]; then
-                  JAVA_HOME=${JDK8}
-              fi
-
-              echo JDK_PARAM=${JDK} >> /home/ubuntu/java.txt
-              echo JDK7=${JDK7} >> /home/ubuntu/java.txt
-              echo JDK8=${JDK8} >> /home/ubuntu/java.txt
-              echo JAVA_HOME=${JAVA_HOME} >> /home/ubuntu/java.txt
-
-              JAVA_HOME_FOUND=$(grep -r "JAVA_HOME=" /etc/environment | wc -l  )
-              echo ">> Setting up JAVA_HOME ..."
-              if [ ${JAVA_HOME_FOUND} = 0 ]; then
-                  echo ">> Adding JAVA_HOME entry."
-                  echo JAVA_HOME=${JAVA_HOME} >> /etc/environment
-              else
-                  echo ">> Updating JAVA_HOME entry."
-                  sed -i "/JAVA_HOME=/c\JAVA_HOME=${JAVA_HOME}" /etc/environment
-              fi
-              source /etc/environment
-
-              echo ">> Setting java userPrefs ..."
-              mkdir -p /tmp/.java/.systemPrefs
-              mkdir /tmp/.java/.userPrefs
-              sudo -u ${USERNAME} chmod -R 755 /tmp/.java
-              echo "export JAVA_HOME=$JAVA_HOME" >> /etc/profile
-              echo "export JAVA_OPTS='-Djava.util.prefs.systemRoot=/tmp/.java/ -Djava.util.prefs.userRoot=/tmp/.java/.userPrefs'" >> /etc/profile
-              source /etc/profile
-          }
       Tags:
         - Key: Name
           Value: wso2-apim-intg-node
